In [2]:
!git clone https://github.com/AnalyticsKnight/yemoonsaBigdata/

Cloning into 'yemoonsaBigdata'...
remote: Enumerating objects: 637, done.
remote: Counting objects: 100% (276/276), done.
remote: Compressing objects: 100% (167/167), done.
remote: Total 637 (delta 137), reused 184 (delta 109), pack-reused 361
Receiving objects: 100% (637/637), 10.76 MiB | 16.11 MiB/s, done.
Resolving deltas: 100% (321/321), done.


In [2]:
import numpy as np
import pandas as pd
import sklearn

In [3]:
from sklearn.datasets import load_iris  # sklearn 제공 데이터셋

In [4]:
iris = load_iris()
print(type(iris))

keys = iris.keys()
print(keys)

<class 'sklearn.utils._bunch.Bunch'>
dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])


In [ ]:
print('feature_names :')
print(iris.feature_names)
print('\ntarget_names :')
print(iris.target_names)
print('\ndata :')
print(iris.data)
print('\ntarget :')
print(iris.target)

In [ ]:
# 데이터프레임으로 변환
iris_df = pd.DataFrame(data = iris.data, columns = iris.feature_names)
iris_df['label'] = iris.target
print(iris_df)

In [7]:
# 학습용 데이터, 테스트 데이터 분리
from sklearn.model_selection import train_test_split  # 학습데이터, 테스트데이터 분할 패키지?

iris_data = iris.data     # 피처데이터
iris_label = iris.target  # 타겟데이터

# iris_data -> feature 데이터셋, iris_label -> target 데이터셋, test_size = 0.2 -> 테스트 데이터 비율
x_train, x_test, y_train, y_test = train_test_split(iris_data, iris_label, test_size = 0.2, random_state = 11)

print('iris_data : ',len(iris.data))     # 150 -> 120:30 ?
print('iris_label : ',len(iris.target))  # 150 -> 120:30 ?
print('train dataset')
print('x_train dataset :', len(x_train))  # 학습 피처 데이터
print('y_train dataset :', len(y_train))  # 학습 타겟 데이터
print('\ntest dataset :')
print('x_test dataset :', len(x_test))    # 테스트 피처 데이터
print('y_test dataset :', len(y_test))    # 테스트 타겟 데이터

iris_data :  150
iris_label :  150
train dataset
x_train dataset : 120
y_train dataset : 120

test dataset :
x_test dataset : 30
y_test dataset : 30


In [8]:
# 의사결정 트리 머신러닝 학습
from sklearn.tree import DecisionTreeClassifier

dt_clf = DecisionTreeClassifier(random_state=11)  # DecisionTreeClassifier를 객체로 생성
dt_clf.fit(x_train, y_train)  # 객체의 fit 함수에 학습 피처 데이터 x_train 함수와 학습 타겟 데이터 y_train을 입력

DecisionTreeClassifier(random_state=11)

In [9]:
# 의사결정 트리 머신러닝 테스트/평가
from sklearn.metrics import accuracy_score

pred = dt_clf.predict(x_test)            # 테스트 피처 데이터로 예측
ac_score = accuracy_score(y_test, pred)  # accuracy_score(테스트 타겟 데이터 세트, 예측 데이터 세트) -> 정확도 측정 함수

print('예측 정확도 :', ac_score)

예측 정확도 : 0.9333333333333333


# 데이터 전처리 연습

## 레이블 인코딩, 원-핫 인코딩

In [15]:
# 레이블 인코딩
from sklearn.preprocessing import LabelEncoder

items = ['TV','냉장고','전자레인지','컴퓨터','TV','냉장고','컴퓨터','컴퓨터']

encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)  # labels.shape -> (8,)

print('인코딩 변환값 : ', labels)            # ['TV' '냉장고' '전자레인지' '컴퓨터'] -> TV: 0, 냉장고: 1, 전자레인지: 2, 컴퓨터: 3 -> [0 1 2 3 0 1 3 3]
print('인코딩 클래스 : ', encoder.classes_)  # 속성값 확인.

# 레이블 디코딩
origins = encoder.inverse_transform([0,1,2,3,0,1,3,3])

print('디코딩 원본값 : ', origins)

인코딩 변환값 :  [0 1 2 3 0 1 3 3]
인코딩 클래스 :  ['TV' '냉장고' '전자레인지' '컴퓨터']
디코딩 원본값 :  ['TV' '냉장고' '전자레인지' '컴퓨터' 'TV' '냉장고' '컴퓨터' '컴퓨터']


In [19]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

labels = labels.reshape(-1,1)  # 위에서 수행한 레이블 인코딩 결과를 2차원 데이터로 변환  -1로 하면 배열 크기를 자동으로 계산

oh_encoder = OneHotEncoder()
oh_encoder.fit(labels)
oh_labels = oh_encoder.transform(labels)

print('원-핫 인코딩 데이터')
print(oh_labels.toarray())
print('원-핫 인코딩 데이터 차원')
print(oh_labels.shape)  # (8,4) 2차원  3차원은 (8,4,1) 이런 형태

원-핫 인코딩 데이터
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]]
원-핫 인코딩 데이터 차원
(8, 4)


In [22]:
# pandas의 원-핫 인코딩
import pandas as pd

item_df = pd.DataFrame({'item' : items})
pd.get_dummies(item_df)  # 명목형 데이터를 숫자형으로 직접 바꾸는 과정을 생략하고 바로 해줌

item_TV  item_냉장고  item_전자레인지  item_컴퓨터
0        1         0           0         0
1        0         1           0         0
2        0         0           1         0
3        0         0           0         1
4        1         0           0         0
5        0         1           0         0
6        0         0           0         1
7        0         0           0         1

## 표준화, 정규화

In [24]:
# 스케일링 데이터 살펴보기
from sklearn.datasets import load_iris  # scikit-learn 라이브러리에서 load_iris 함수를 가져옴
import pandas as pd

iris = load_iris()      # load_iris 함수를 사용하여 Iris 데이터셋을 로드하고, 그 결과를 iris 변수에 저장
iris_data = iris.data   # iris 객체에서 데이터 포인트(샘플)의 특징(feature) 데이터를 가져와서 iris_data 변수에 저장
iris_df = pd.DataFrame(data = iris_data, columns = iris.feature_names)

print('feature 들의 평균 값 : \n', iris_df.mean())
print('feature 들의 분산 값 : \n', iris_df.var())

feature 들의 평균 값 : 
 sepal length (cm)    5.843333
sepal width (cm)     3.057333
petal length (cm)    3.758000
petal width (cm)     1.199333
dtype: float64
feature 들의 분산 값 : 
 sepal length (cm)    0.685694
sepal width (cm)     0.189979
petal length (cm)    3.116278
petal width (cm)     0.581006
dtype: float64


In [25]:
# 표준화
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaler.fit(iris_df)
iris_scaled = scaler.transform(iris_df)
iris_df_scaled = pd.DataFrame(data = iris_scaled, columns = iris.feature_names)

print('feature 들의 평균 값 : \n', iris_df_scaled.mean())
print('feature 들의 분산 값 : \n', iris_df_scaled.var())

# 평균은 0에 분산은 1에 가까워짐

feature 들의 평균 값 : 
 sepal length (cm)   -1.690315e-15
sepal width (cm)    -1.842970e-15
petal length (cm)   -1.698641e-15
petal width (cm)    -1.409243e-15
dtype: float64
feature 들의 분산 값 : 
 sepal length (cm)    1.006711
sepal width (cm)     1.006711
petal length (cm)    1.006711
petal width (cm)     1.006711
dtype: float64


In [26]:
# 최대-최소 정규화
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
scaler.fit(iris_df)
iris_scaled = scaler.transform(iris_df)
iris_df_scaled = pd.DataFrame(data = iris_scaled, columns = iris.feature_names)

print('feature 들의 최소 값 : \n', iris_df_scaled.min())
print('feature 들의 최대 값 : \n', iris_df_scaled.max())

feature 들의 최소 값 : 
 sepal length (cm)    0.0
sepal width (cm)     0.0
petal length (cm)    0.0
petal width (cm)     0.0
dtype: float64
feature 들의 최대 값 : 
 sepal length (cm)    1.0
sepal width (cm)     1.0
petal length (cm)    1.0
petal width (cm)     1.0
dtype: float64


In [30]:
# 스케일링 주의사항 (fit은 학습 데이터로만?)
from sklearn.preprocessing import MinMaxScaler
import numpy as np

train_array = np.arange(0,11).reshape(-1,1)
test_array = np.arange(0,6).reshape(-1,1)

scaler = MinMaxScaler()
scaler.fit(train_array)
train_scaled = scaler.transform(train_array)

print('원본 train_array 데이터 : ', np.round(train_array.reshape(-1),2))
print('Scaled train_array 데이터 : ', np.round(train_scaled.reshape(-1),2))

# scaler.fit(test_array)  학습 데이터로 fit을 했기 때문에 test데이터로는 fit을 진행하지 않음
test_scaled = scaler.transform(test_array)

print('\n원본 test_array 데이터 : ', np.round(test_array.reshape(-1),2))
print('Scaled test_array 데이터 : ', np.round(test_scaled.reshape(-1),2))

# 1. MinMaxScaler를 scaler로 생성

# 2. scaler.fit(train_array)를 사용하여 scaler를 학습 데이터(train_array)에 맞춤.
# 이 단계에서 scaler는 학습 데이터의 최솟값과 최댓값을 계산.

# 3. train_scaled = scaler.transform(train_array)를 사용하여 학습 데이터를 변환하여 train_scaled 생성
# 이 단계에서 train_array의 값들이 최솟값과 최댓값을 이용하여 0과 1 사이의 값으로 스케일링.

# 4. test_scaled = scaler.transform(test_array)를 사용하여 테스트 데이터(test_array)를 변환하여 test_scaled 생성
# 이 때, 테스트 데이터도 학습 데이터에서 계산된 최솟값과 최댓값을 사용하여 0과 1 사이의 값으로 스케일링

# 이렇게 해야 학습 데이터와 테스트 데이터가 동일한 스케일링 방식을 공유

MinMaxScaler()
MinMaxScaler()
원본 train_array 데이터 :  [ 0  1  2  3  4  5  6  7  8  9 10]
Scaled train_array 데이터 :  [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]

원본 test_array 데이터 :  [0 1 2 3 4 5]
Scaled test_array 데이터 :  [0.  0.1 0.2 0.3 0.4 0.5]


# 전체적인 분석 과정 연습

In [2]:
# 1. 데이터 불러오기 (csv파일 불러오기)
import pandas as pd

data = pd.read_csv("./yemoonsaBigdata/datasets/Part2/housing_data.csv", header = None, sep=',')
col_names = ['CRIM','ZN','INDUS','CHAS','NOX','RM','AGE','DIS','RAD','TAX','PTRATIO','B','LSTAT','MEDV','isHighValue']
data.columns = col_names

data.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296.0   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242.0   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242.0   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222.0   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222.0   

   PTRATIO       B  LSTAT  MEDV  isHighValue  
0     15.3  396.90   4.98  24.0            0  
1     17.8  396.90   9.14  21.6            0  
2     17.8  392.83   4.03  34.7            1  
3     18.7  394.63   2.94  33.4            1  
4     18.7  396.90   5.33  36.2            1

In [ ]:
# 2. 데이터 전처리 (데이터 확인 - 결측치 처리 - 이상치 처리 - 변수 변환)

# 2.1 데이터 확인
print(data.shape)
print(data.info())
print(data.describe())

# 2.2 결측치 확인
print(data.isnull().sum())
print(data.isnull().sum()/data.shape[0])  # 결측치 비율 확인  data.shape[0] -> 행의 개수?

# 결측치 대체(중앙값)
data1 = data.copy()
med_val = data['CRIM'].median()  # CRIM의 중앙값
data1['CRIM'] = data1['CRIM'].fillna(med_val) # 중앙값으로 결측치 대체

# data.loc[행의조건, 열의조건]
data = data.loc[data['CRIM'].notnull(),]  # CRIM이 null이 아닌 행만 선택, 열 조건은 생략해서 모든 열 선택
print(data.describe)
# 결측치를 제거할 경우 dropna 사용

In [ ]:
# 2.3 이상치 확인 (IQR, 비율 확인)
import seaborn as sns
sns.boxplot(data['MEDV'])

Q1,Q3 = data['MEDV'].quantile([0.25,0.75])
IQR = Q3 - Q1  # 사분위수 범위
upper_bound = Q3 +1.5*IQR  # 큰 이상치 기준
lower_bound = Q1 -1.5*IQR  # 작은 이상치 기준

print('outlier 범위 : %.2f 초과 또는 %.2f 미만' % (upper_bound, lower_bound))  # %.2f -> 소수점 아래 두자리까지 표시
print('outlier 개수 : %.0f'% len(data[(data['MEDV']>upper_bound)|(data['MEDV']<lower_bound)]))
print('outlier 비율 : %.2f'% (len(data[(data['MEDV']>upper_bound)|(data['MEDV']<lower_bound)])/len(data)))

# 이상치 제거
data1 = data[(data['MEDV']<= upper_bound)&(data['MEDV']>=lower_bound)]  # 이상치 기준 사이의 값들만 data1로 저장
data2 = data[~(data['MEDV']>=45)] # MEDV값이 45 이상인 경우 이상치로 보고 제거 / ~은 not의 의미 45 이상이 아닌 MEDV만 선택

In [ ]:
# IQR 값 기준 이상치 함수화 방법
def get_outlier_prop(x):
  Q1, Q3 = x.quantile([0.25,0.75])
  IQR = Q3 - Q1
  upper_bound = Q3 + 1.5 * IQR
  lower_bound = Q1 - 1.5 * IQR
  outliers = x[(x>upper_bound)|(x<lower_bound)]
  return str(round(100 * len(outliers)/len(x), 1))+'%'

# apply 메서드를 사용하면 데이터프레임의 열 또는 행에 사용자 지정 함수를 적용하여
# 데이터를 변환하거나 요약하는 작업을 수행
print(data.apply(get_outlier_prop))  # data의 각 열을 get_outlier_prop 함수에 적용

In [ ]:
# 2.4 변수 변환 (로그 변환, 제곱근 변환 등 + 스케일링)

# 변수 분포 확인
import matplotlib.pyplot as plt
import seaborn as sns

cols = data.columns

fig, axs = plt.subplots(ncols = 5, nrows = 3, figsize = (20,10))  # 3행 5열로 총 15개 서브플롯 생성
idx = 0  # 서브플롯을 순서대로 채우기 위한 인덱스 변수 초기화?
for _row in range(3):
  for _col in range(5):
    if idx < len(cols):
      sns.distplot(data[cols[idx]], ax = axs[_row][_col])
      idx += 1
plt.tight_layout()

# 변수 왜도 확인 (왜도 절댓값이 3이상이면 크게 치우쳐져 있다고 판단)
print(data.apply(lambda x : x.skew(), axis = 0))  # lambda -> 간단한 함수를 인라인으로 정의할 때 사용?

# 로그 변환
import numpy as np

# 로그 변환은 양수만 가능하니까 1p(1+) 해줌 -> np.log1p(data['CRIM']) = np.log(data['CRIM']+1)
data['CRIM'] = np.log1p(data['CRIM'])
print(data['CRIM'].skew())

In [ ]:
# 3. 회귀 모델링

# 3.1 데이터 생성 및 탐색  (종속변수 MEDV)
df_r = data.drop(['isHighValue'], axis = 1)

# 변수 상관관계 확인
cols = ['MEDV','LSTAT','RM','CHAS','RAD','TAX']
print(df_r[cols].corr())
# 상관계수 확인 결과 종속변수 MEDV와 강한 상관관계를 가지는 변수는 LSTAT과 RM으로 나타남
# 하지만 LSTAT과 RM이 서로 상관관계가 높으므로 다중공선성을 갖음
# 이런 경우 둘 중 하나의 변수만 사용하거나 주성분 분석등의 방법을 사용함

# 3.2 분석 모형 구축

# 3.2.1 데이터 분할
from sklearn.model_selection import train_test_split

X_cols = ['LSTAT','PTRATIO','TAX','AGE','NOX','INDUS','CRIM']

X = df_r[X_cols].values
y = df_r['MEDV'].values

# (x,y,test_size, random_state) -> x: 특성 데이터(변수?), y: 타겟 변수(집값)
# X_train: 훈련 데이터의 특성(피처) 행렬.
# X_test: 테스트 데이터의 특성 행렬.
# y_train: 훈련 데이터의 타겟(목표) 변수(출력).
# y_test: 테스트 데이터의 타겟 변수.
X_train_r, X_test_r, y_train_r, y_test_r = train_test_split(X, y, test_size = 0.3, random_state = 123)

# train_test_split(X, y, test_size = 0.3, random_state = 123) 실행하면 4개의 값을 반환하고
# 그 값을 X_train_r, X_test_r, y_train_r, y_test_r 에 저장하는 코드?

# 3.2.2 데이터 스케일링
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

X_train_r_scaled = scaler.fit_transform(X_train_r)
X_test_r_scaled = scaler.fit_transform(X_test_r)

In [ ]:
# 3.2.3 모델 구축 (선형 회귀, SVM, 랜덤포레스트)

# 선형 회귀
from sklearn.linear_model import LinearRegression

model_lr = LinearRegression()
model_lr.fit(X_train_r_scaled, y_train_r)

# 선형 회귀 모델의 계수와 절편 확인
print(model_lr.coef_)  # 계수?
print(model_lr.intercept_) # 절편

# SVM
from sklearn.svm import SVR

model_svr = SVR()
model_svr.fit(X_train_r_scaled, y_train_r)

# 랜덤포레스트
from sklearn.ensemble import RandomForestRegressor

model_rfr = RandomForestRegressor(random_state = 123)
model_rfr.fit(X_train_r_scaled, y_train_r)

# rfr? 모델에서 사용하는 변수 중요도 확인 방법
for x, val in zip(X_cols, model_rfr.feature_importances_):
  print(f'{x} : %.3f' %val)

In [47]:
# 3.3 분석 모형 평가 (평가 지표 중 MAE, MSE, MAPE 사용)

# 예측값 생성
y_pred_lr = model_lr.predict(X_test_r_scaled)
y_pred_svr = model_svr.predict(X_test_r_scaled)
y_pred_rfr = model_rfr.predict(X_test_r_scaled)

# 평가 지표 계산 (MAE, MSE, MAPE)
from sklearn.metrics import mean_absolute_error, mean_squared_error, mean_absolute_percentage_error

print('-'*30)
print('선형 회귀 결과')
print('MAE : %.3f' %mean_absolute_error(y_test_r, y_pred_lr))
print('MSE : %.3f' %mean_squared_error(y_test_r, y_pred_lr))
print('MAPE : %.3f' %mean_absolute_percentage_error(y_test_r, y_pred_lr))
print('-'*30)
print('SVM 결과')
print('MAE : %.3f' %mean_absolute_error(y_test_r, y_pred_svr))
print('MSE : %.3f' %mean_squared_error(y_test_r, y_pred_svr))
print('MAPE : %.3f' %mean_absolute_percentage_error(y_test_r, y_pred_svr))
print('-'*30)
print('랜덤포레스트 결과')
print('MAE : %.3f' %mean_absolute_error(y_test_r, y_pred_rfr))
print('MSE : %.3f' %mean_squared_error(y_test_r, y_pred_rfr))
print('MAPE : %.3f' %mean_absolute_percentage_error(y_test_r, y_pred_rfr))
print('-'*30)

------------------------------
선형 회귀 결과
MAE : 4.358
MSE : 35.076
MAPE : 0.219
------------------------------
SVM 결과
MAE : 3.886
MSE : 37.733
MAPE : 0.173
------------------------------
랜덤포레스트 결과
MAE : 3.165
MSE : 20.694
MAPE : 0.156
------------------------------


In [ ]:
# 4. 분류 모델링

# 4.1 데이터 생성 및 탐색  (종속변수 isHIghValue)
df_c = data.drop(['MEDV'], axis = 1)

import seaborn as sns
# LSTAT 변수 박스플롯
# sns.boxplot(x = 'isHighValue', y = 'LSTAT', data = df_c)

#LSTAT 변수 kde플롯  / 박스플롯이랑 따로 실행해야 나옴
sns.kdeplot(df_c.loc[df_c['isHighValue']==1, 'LSTAT'], color = 'orange', fill = True)
sns.kdeplot(df_c.loc[df_c['isHighValue']==0, 'LSTAT'], color = 'blue', fill = True)

# 시험에서는 시각화를 사용할 수 없어서 종속변수에 따른 각 독립변수의 평균값(또는 백분위수)을 구하여 유효한 변수 구하기
import numpy as np

print(df_c.groupby('isHighValue').apply(np.mean).T)
# T: 전치(transpose) 연산을 수행. 이는 데이터프레임의 행과 열을 바꿔줌. 2행 3열 -> 3행 2열
# 즉, 그룹별 평균이 행이 아니라 열로 나타냄, Pandas에서 사용 가능한 속성

In [9]:
# 4.2 분석 모형 구축

# 4.2.1 데이터 분할
from sklearn.model_selection import train_test_split

X_cols = ['LSTAT','PTRATIO','TAX','AGE','NOX','INDUS','CRIM']

X = data[X_cols].values
y = data['isHighValue'].values

X_train_c, X_test_c, y_train_c, y_test_c = train_test_split(X, y, test_size = 0.3, random_state = 123)

# 4.2.2 데이터 스케일링
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

X_train_c_scaled = scaler.fit_transform(X_train_c)
X_test_c_scaled = scaler.fit_transform(X_test_c)

In [14]:
# 4.2.3 모델 구축 (로지스틱 회귀, SVM, 랜덤포레스트)

# 로지스틱 회귀 학습
from sklearn.linear_model import LogisticRegression

model_lo = LogisticRegression()
model_lo.fit(X_train_c_scaled, y_train_c)

# 로지스틱 회귀 모델의 계수와 절편 확인
print(model_lo.coef_)  # 계수?
print(model_lo.intercept_) # 절편

# SVM
from sklearn.svm import SVC

model_svc = SVC(probability=True)  # probability=True는 SVC 모델이 클래스 확률을 제공할 수 있도록 하는 옵션
model_svc.fit(X_train_c_scaled, y_train_c)

# 랜덤포레스트
from sklearn.ensemble import RandomForestClassifier

model_rfc = RandomForestClassifier(random_state = 123)
model_rfc.fit(X_train_c_scaled, y_train_c)

# rfc? 모델에서 사용하는 변수 중요도 확인 방법
for x, val in zip(X_cols, model_rfc.feature_importances_):
  print(f'{x} : %.3f' %val)

[[-4.67917856 -2.26271976 -0.80852617  0.45926521 -0.32914015 -1.36930599
   0.86834454]]
[1.90334599]
LSTAT : 0.378
PTRATIO : 0.105
TAX : 0.112
AGE : 0.087
NOX : 0.080
INDUS : 0.134
CRIM : 0.104


In [ ]:
# 4.3 분석 모형 평가

# 예측값 생성  threshold가 0.5인 상태로 예측값을 구하고 0.5 이상은 1 아니면 0인 결과를 얻음
y_pred_lo = model_lo.predict(X_test_c_scaled)
y_pred_svc = model_svc.predict(X_test_c_scaled)
y_pred_rfc = model_rfc.predict(X_test_c_scaled)

# 평가 지표 계산 (평가 지표 accuracy_score, precision_score, recall_score -> classification_report 한번에 계산 가능)
from sklearn.metrics import classification_report

print('-'*60)
print('로지스틱 회귀 결과')
print(classification_report(y_test_c, y_pred_lo, labels = [0,1]))
print('-'*60)
print('SVM 결과')
print(classification_report(y_test_c, y_pred_svc, labels = [0,1]))
print('-'*60)
print('랜덤포레스트 결과')
print(classification_report(y_test_c, y_pred_rfc, labels = [0,1]))
print('-'*60)

In [19]:
# AUROC 계산
from sklearn.metrics import roc_auc_score

y_pred_lo = model_lo.predict_proba(X_test_c_scaled)[:, 1]
y_pred_svc = model_svc.predict_proba(X_test_c_scaled)[:, 1]
y_pred_rfc = model_rfc.predict_proba(X_test_c_scaled)[:, 1]
# 위에서 0.5 이상은 1 미만은 0으로 이진 분류를 했으니까 1인 확률?을 구하는거?
# ROC-AUC 점수가 높을수록 분류 능력 우수함,(곡선 아래 면적 구하는 뭐였는데)

print('로지스틱 회귀 결과 : %.3f' %roc_auc_score(y_test_c,y_pred_lo))
print('SVM 결과 : %.3f' %roc_auc_score(y_test_c,y_pred_svc))
print('랜덤포레스트 결과 : %.3f' %roc_auc_score(y_test_c,y_pred_rfc))

로지스틱 회귀 결과 : 0.914
SVM 결과 : 0.936
랜덤포레스트 결과 : 0.959


StandardScaler (표준 스케일러):

평균이 0이고 표준 편차가 1인 정규 분포 형태로 스케일링됩니다.
이상치(outliers)에 영향을 덜 받습니다.
주로 선형 모델(선형 회귀, 로지스틱 회귀) 및 기타 거리 기반 모델 (K-최근접 이웃, 서포트 벡터 머신)에 사용됩니다.

MinMaxScaler (최소-최대 스케일러):

데이터를 0과 1 사이의 범위로 스케일링합니다.
데이터가 양수 값으로 제한되어 있고, 다른 스케일러를 사용하면 이해하기 어려울 때 사용됩니다.
딥러닝 모델 (신경망) 및 기타 모델에 사용됩니다.

RobustScaler (로버스트 스케일러):

이상치(outliers)에 대해 강건한 스케일링을 제공합니다.
중앙값(median)과 IQR (Interquartile Range)을 사용하여 스케일링합니다.
데이터에 이상치가 많이 포함된 경우에 유용합니다.

QuantileTransformer (분위수 변환):

데이터를 주어진 분위수에 따라 변환합니다.
데이터를 정규 분포에 가깝게 스케일링하는 데 사용됩니다.

# 실습

## 실습1: Moter Trend Car Road Tests

In [ ]:
# 기본 제공 코드
import numpy as np
import pandas as pd
X_test = pd.read_csv('./yemoonsaBigdata/datasets/Part2/mpg_X_test.csv')
X_train = pd.read_csv('./yemoonsaBigdata/datasets/Part2/mpg_X_train.csv')
y_train = pd.read_csv('./yemoonsaBigdata/datasets/Part2/mpg_y_train.csv')

In [ ]:
# 1. 데이터 전처리

# 데이터 확인 (결측치, 데이터 타입 확인)
X_train.info()  # horsepower에 3개의 결측치가 있음, 데이터 타입 변경 필요 없음

# 결측치 채우기
from sklearn.impute import SimpleImputer  # SimpleImputer 함수로 결측치 변경

imputer = SimpleImputer(missing_values = np.nan, strategy = 'mean')  # strategy: 통계값이나 상수 입력
X_train[['horsepower']] = imputer.fit_transform( X_train[['horsepower']]) # imputer를 사용하여 'horsepower' 열에서 결측값을 대체
X_test[['horsepower']] = imputer.fit_transform( X_test[['horsepower']])   # fit_transform 메서드는 결측값을 대체하는 작업을 수행

# 데이터 확인 (이상치 확인, 수치형 데이터 고르기?)
X_train.describe()  # 특별한 이상치 없음

# 변수 형태별 리스트 저장 (수치형 데이터만 선택)
COL_DEL = ['name']
COL_NUM = ['mpg','cylinders','displacement','horsepower','weight','acceleration','model_year']
COL_CAT = []
COL_Y = ['isUSA']

X_train = X_train.iloc[:,1:]  # 첫 번째 열(name)을 제외한 모든 열 선택
X_test = X_test.iloc[:,1:]    # 첫 번째 열(name)을 제외한 모든 열 선택

In [25]:
# 2. 데이터 모형 구축
from sklearn.model_selection import train_test_split
X_tr, X_val, y_tr, y_val = train_test_split(X_train, y_train, test_size = 0.3)

# 스케일링 진행
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaler.fit(X_tr[COL_NUM])
X_tr[COL_NUM]= scaler.transform(X_tr[COL_NUM])
X_val[COL_NUM]= scaler.transform(X_val[COL_NUM])
X_test[COL_NUM]= scaler.transform(X_test[COL_NUM])

In [35]:
# 3. 모델 학습(KNN, 의사결정나무 모형)

# KNN
from sklearn.neighbors import KNeighborsClassifier
modelKNN = KNeighborsClassifier(n_neighbors = 5, metric = 'euclidean')
modelKNN.fit(X_tr, y_tr.values.ravel())

# 의사결정나무 모형
from sklearn.tree import DecisionTreeClassifier
modelDT = DecisionTreeClassifier(max_depth = 10)
modelDT.fit(X_tr, y_tr)

DecisionTreeClassifier(max_depth=10)

In [36]:
# 4. 모델 평가
y_val_pred = modelKNN.predict(X_val)

y_val_pred_probaKNN = modelKNN.predict_proba(X_val)
y_val_pred_probaDT = modelDT.predict_proba(X_val)

# roc-auc_score 확인
from sklearn.metrics import roc_auc_score

scoreKNN = roc_auc_score(y_val, y_val_pred_probaKNN[:,1])
scoreDT = roc_auc_score(y_val, y_val_pred_probaDT[:,1])

print(scoreKNN, scoreDT)

0.8723404255319149 0.8059229442208166


In [43]:
# 하이퍼파라미터를 학습하는 모형을 저장하여 가장 높은 모형을 선택하는 코드
best_model = None
best_score = 0

for i in range(2, 10):
    model = KNeighborsClassifier(n_neighbors=i, metric='euclidean')
    model.fit(X_tr, y_tr.values.ravel())
    y_val_pred_proba = model.predict_proba(X_val)
    score = roc_auc_score(y_val, y_val_pred_proba[:, 1])
    print(i, '개의 이웃 확인 :', score)
    if best_score <= score:
        best_score = score  # Update best_score
        best_model = model  # Update best_model

print("최적의 이웃 개수:", best_model.n_neighbors)
print("최적의 ROC-AUC 점수:", best_score)

2 개의 이웃 확인 : 0.8461759631972399
3 개의 이웃 확인 : 0.8594019551466359
4 개의 이웃 확인 : 0.8539390454284072
5 개의 이웃 확인 : 0.8723404255319149
6 개의 이웃 확인 : 0.886428982173663
7 개의 이웃 확인 : 0.8933294997124784
8 개의 이웃 확인 : 0.8898792409430708
9 개의 이웃 확인 : 0.8815411155836688
최적의 이웃 개수: 7
최적의 ROC-AUC 점수: 0.8933294997124784


In [46]:
# 제출물 만들기
# print(best_model.predict_proba(X_test))  # 2열에서 1이 isUSA인 경우로 2열을 추출해야함

pred = best_model.predict_proba(X_test)[:,1]
print(pred)

# 제출용 파일 저장
pd.DataFrame({'isUSA': pred}).to_csv('./yemoonsaBigdata/res/00300000.csv', index=False)

[0.42857143 0.57142857 1.         1.         0.42857143 0.28571429
 0.14285714 0.28571429 0.42857143 0.57142857 1.         0.42857143
 1.         0.57142857 0.14285714 0.28571429 1.         1.
 0.14285714 1.         1.         1.         1.         1.
 1.         0.42857143 0.14285714 1.         1.         0.57142857
 0.14285714 0.14285714 0.57142857 0.85714286 1.         0.57142857
 0.85714286 1.         0.14285714 0.57142857 1.         0.
 0.14285714 0.71428571 0.42857143 0.42857143 0.42857143 1.
 0.28571429 1.         0.         0.14285714 1.         0.14285714
 1.         1.         1.         0.71428571 1.         0.28571429
 0.85714286 0.85714286 1.         1.         0.85714286 1.
 1.         0.28571429 0.85714286 0.14285714 1.         1.
 0.71428571 0.         1.         0.28571429 1.         0.14285714
 0.42857143 1.         1.         1.         0.14285714 1.
 1.         1.         0.         0.14285714 0.28571429 1.
 1.         1.         1.         1.         1.         1.


## 실습2: Penguins

In [3]:
# 사전 준비
import pandas as pd
import numpy as np
import warnings

warnings.filterwarnings('ignore')  # 코드 실행에 직접적인 문제가 되지 않는 경고문 생략

X_test = pd.read_csv('./yemoonsaBigdata/datasets/Part2/penguin_X_test.csv')
X_train = pd.read_csv('./yemoonsaBigdata/datasets/Part2/penguin_X_train.csv')
y_train = pd.read_csv('./yemoonsaBigdata/datasets/Part2/penguin_y_train.csv')

In [ ]:
# 1. 데이터 전처리
X_train.info()

# 결측치가 존재하는 데이터 확인 (X와 y를 합쳐서 확인)
train = pd.concat([X_train, y_train], axis=1)  # train에 X_train, y_train을 열 방향으로 합침(옆으로 합쳐짐) * 두 데이터의 행의 수가 같아야 합치기 가능?
print(train.loc[(train.sex.isna())|(train.bill_length_mm.isna())|(train.bill_depth_mm.isna())|
 (train.flipper_length_mm.isna())|(train.body_mass_g.isna())])
# train.sex.isna() -> 결측값의 유무를 불리언 시리즈 생성
# train.loc -> 생성된 불리언 시리즈로 True값만 가져옴(결측값만 가져오게됨)

# 위 코드 나눠서 실행하면 이해하기 쉬움
# 1. train.sex.isna()
# 2. train.loc[train.sex.isna()]

# 결측치 제거하기
train = train.dropna()                      # 제거된 행의 인덱스가 비게됨
train.reset_index(drop=True, inplace=True)  # 그니까 인덱스 리셋해주기

# 다시 데이터를 나누기
X_train = train[['species','island','sex','bill_length_mm','bill_depth_mm','flipper_length_mm']]
y_train = train[['body_mass_g']]

# 통계량 확인
X_train.describe() # 별 이상 없음

In [ ]:
# 범주형 데이터, 수치형 데이터, 종속변수 데이터 나누기
COL_DEL = []
COL_NUM = ['bill_length_mm','bill_depth_mm','flipper_length_mm']
COL_CAT = ['species','island','sex']
COL_Y = ['body_mass_g']

# 범주형 데이터 원-핫 인코딩 train과 test 합친 후 진행.
X = pd.concat([X_train, X_test])

from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder(handle_unknown='ignore')  # handle_unknown -> transform을 진행 할 때 첨보는 변수 어떻게 처리할 지 결정. 이미 앞에서 처리해서 무시하기로 함
ohe.fit(X[COL_CAT])

X_train_res = ohe.transform(X_train[COL_CAT])
X_test_res = ohe.transform(X_test[COL_CAT])

print(X_train_res) # 데이터프레임이 아닌 행렬을 줄요서 표현한 데이터임을 확인할 수 있음

# 변환된 데이터를 데이터프레임 형식으로 바꾸기? 버전 때문에 교재와 다름
X_train_ohe = pd.DataFrame(X_train_res.todense(), columns=ohe.get_feature_names_out(input_features=COL_CAT))
X_test_ohe = pd.DataFrame(X_test_res.todense(), columns=ohe.get_feature_names_out(input_features=COL_CAT))
print(X_train_ohe)  # -> 변환된 범주형 데이터 생성됨

# 새로 생성한 범주형 데이터와 숫자형 데이터를 합쳐줌
X_train_fin = pd.concat([X_train[COL_NUM], X_train_ohe], axis = 1)
X_test_fin = pd.concat([X_test[COL_NUM], X_test_ohe], axis = 1)

In [ ]:
# 2. 데이터 모형 구축

# 학습데이터, 테스트 데이터 분류
from sklearn.model_selection import train_test_split
X_tr, X_val, y_tr, y_val = train_test_split(X_train_fin, y_train, test_size = 0.3)

# 수치형 변수에 대해 스케일링
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
scaler.fit(X_tr[COL_NUM])   # fit을 할 땐 X_tr만 사용
X_tr[COL_NUM] = scaler.transform(X_tr[COL_NUM])
X_val[COL_NUM] = scaler.transform(X_val[COL_NUM])
X_test_fin[COL_NUM] = scaler.transform(X_test_fin[COL_NUM])

# 선형 회귀모델로 학습
from sklearn.linear_model import LinearRegression

modelLR = LinearRegression()
modelLR.fit(X_tr, y_tr)

# 학습 결과 출력?
y_val_pred = modelLR.predict(X_val)
print(y_val_pred)

# intercept와 coef 사용하여 절편과 기울기 구하기
print(modelLR.intercept_)  # [3271.3123242]

coef = pd.Series(data = modelLR.coef_[0], index = X_train_fin.columns)
print(coef.sort_values())

In [14]:
# 3. 데이터 모형 평가

# 평가지표 : RMSE (MSE의 제곱근)
from sklearn.metrics import mean_squared_error, r2_score

mse = mean_squared_error(y_val, y_val_pred)
rmse = mean_squared_error(y_val, y_val_pred, squared = False)

print('MSE : {0:.3f}, RMSE : {1:.3F} '.format(mse, rmse))

MSE : 78655.229, RMSE : 280.455 


In [ ]:
# 4. 제출물 만들기
y_pred = modelLR.predict(X_test_fin)
print(y_pred)

pd.DataFrame({'body_mass_g': y_pred[:,0]}).to_csv('./yemoonsa/Bigdata/res/00400000.csv', index = False)